// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAUUGs0dHFY6yC7AU541_uT1iA_PP5LjE',
    appId: '1:622886773076:web:cabadf0ff49fbfddd3e8c1',
    messagingSenderId: '622886773076',
    projectId: 'sw-escape-30e60',
    authDomain: 'sw-escape-30e60.firebaseapp.com',
    storageBucket: 'sw-escape-30e60.appspot.com',
    measurementId: 'G-EDF4Z7PLTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPE669DboWHVew5aXIWxICRkvbX-FAJP4',
    appId: '1:622886773076:android:06d917840ec928bad3e8c1',
    messagingSenderId: '622886773076',
    projectId: 'sw-escape-30e60',
    storageBucket: 'sw-escape-30e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS9oawfqcZBCJ0cznsy7MFix2-_NkRMiI',
    appId: '1:622886773076:ios:29c681ea50e56aded3e8c1',
    messagingSenderId: '622886773076',
    projectId: 'sw-escape-30e60',
    storageBucket: 'sw-escape-30e60.appspot.com',
    iosBundleId: 'com.example.swEscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS9oawfqcZBCJ0cznsy7MFix2-_NkRMiI',
    appId: '1:622886773076:ios:d48d38c203e6897cd3e8c1',
    messagingSenderId: '622886773076',
    projectId: 'sw-escape-30e60',
    storageBucket: 'sw-escape-30e60.appspot.com',
    iosBundleId: 'com.example.swEscape.RunnerTests',
  );
}
