// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEErPErcvWhyXpx7nXvUWQrTtQ6ubGSXw',
    appId: '1:805585160668:web:15df3e98a39041374ce719',
    messagingSenderId: '805585160668',
    projectId: 'sw-escape-dbbaa',
    authDomain: 'sw-escape-dbbaa.firebaseapp.com',
    storageBucket: 'sw-escape-dbbaa.appspot.com',
    measurementId: 'G-BRRM7EYY0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv3ekmm0WvLIdN1qL_FEFz9oZH8jC5zDs',
    appId: '1:805585160668:android:cedabd03e6a33d244ce719',
    messagingSenderId: '805585160668',
    projectId: 'sw-escape-dbbaa',
    storageBucket: 'sw-escape-dbbaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFHo1tsC1xETjVKL9j3Z9ElXFdz0Wwyg',
    appId: '1:805585160668:ios:5ff3c9a9261951494ce719',
    messagingSenderId: '805585160668',
    projectId: 'sw-escape-dbbaa',
    storageBucket: 'sw-escape-dbbaa.appspot.com',
    iosBundleId: 'com.example.swEscape',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFHo1tsC1xETjVKL9j3Z9ElXFdz0Wwyg',
    appId: '1:805585160668:ios:41b4357a9beaa9264ce719',
    messagingSenderId: '805585160668',
    projectId: 'sw-escape-dbbaa',
    storageBucket: 'sw-escape-dbbaa.appspot.com',
    iosBundleId: 'com.example.swEscape.RunnerTests',
  );
}
